openapi: 3.0.0
info:
  title: microvent
  version: '1.0'
  description: 「3Dプリント可能な人工呼吸器実用開発研究」に係るスマートフォンアプリの構築、運用・管理
  contact:
    name: shota kawano
    email: kawano@r102.co.jp
servers:
  - url: 'http://api.microvent.r102.jp'
paths:
  /auth/token/generate:
    put:
      summary: 組織内利用者によるログイン
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      user_id:
                        type: number
                      user_name:
                        type: string
                        minLength: 1
                      organization_name:
                        type: string
                        minLength: 1
                      api_token:
                        type: string
                        minLength: 1
                    required:
                      - user_id
                      - user_name
                      - organization_name
                      - api_token
                required:
                  - result
              examples:
                example-1:
                  value:
                    result:
                      user_id: 3
                      user_name: テスト太郎
                      organization_name: テスト組織
                      api_token: '###user_token###'
      operationId: put-auth-token-generate
      description: 組織内利用者によるログイン、ユーザートークン発行
      parameters:
        - schema:
            type: string
          in: header
          name: X-Api-Token
          required: true
          description: 疎通用トークン
        - schema:
            type: string
          in: header
          name: Accept
          description: application/json
          required: true
        - schema:
            type: string
          in: header
          name: Content-Type
          description: application/json; charset=UTF-8
          required: true
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                user:
                  type: string
                  minLength: 1
                  description: ユーザー名もしくはメールアドレス
                password:
                  type: string
                  minLength: 1
              required:
                - user
                - password
      tags:
        - auth
  /ventilator:
    get:
      summary: 人工呼吸器情報取得
      tags:
        - ventilator
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  result:
                    type: object
                    required:
                      - is_registered
                    properties:
                      is_registered:
                        type: boolean
                      ventilator_id:
                        type: number
                      patient_id:
                        type: number
                      organization_name:
                        type: string
                        minLength: 1
                      serial_number:
                        type: number
                required:
                  - result
              examples:
                example-1:
                  value:
                    result:
                      is_registered: true
                      ventilator_id: 1
                      patient_id: 1
                      organization_name: テスト組織
                      serial_number: 1
                example-2:
                  value:
                    result:
                      is_registered: false
      operationId: get-ventilator
      description: |
        GS1コードにより人工呼吸器に紐付いた患者の身長体重情報を取得する。存在しない場合はregistered:falseを返す。
        紐付けがされている場合は、患者IDや組織名も返す。X-User-Tokenが付与されていれば登録済み呼吸器の組織紐付けを行う
      parameters:
        - schema:
            type: string
          in: header
          name: X-Api-Token
          description: 疎通用トークン
          required: true
        - schema:
            type: string
          in: header
          name: Accept
          description: application/json
          required: true
        - schema:
            type: string
          in: query
          name: gs1_code
          description: QR読み取りにより取得される識別コード
          required: true
        - schema:
            type: string
          in: header
          name: X-User-Token
    post:
      summary: 設定データを登録する
      operationId: post-ventilator
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  result:
                    type: object
                    required:
                      - ventilator_id
                      - serial_number
                    properties:
                      ventilator_id:
                        type: number
                      organization_name:
                        type: string
                        minLength: 1
                      serial_number:
                        type: number
                required:
                  - result
              examples:
                example-1:
                  value:
                    result:
                      ventilator_id: 1
                      organization_name: テスト組織
                      serial_number: 1
      parameters:
        - schema:
            type: string
          in: header
          name: X-Api-Token
          description: 疎通用トークン
          required: true
        - schema:
            type: string
          in: header
          name: Accept
          description: application/json
          required: true
        - schema:
            type: string
          in: header
          name: Content-Type
          description: application/json; charset=UTF-8
          required: true
        - schema:
            type: string
          in: header
          name: X-User-Token
          description: ユーザー識別用トークン
          required: true
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                gs1_code:
                  type: string
                  minLength: 1
                latitude:
                  type: string
                  minLength: 1
                longitude:
                  type: string
                  minLength: 1
              required:
                - gs1_code
            examples:
              example-1:
                value:
                  gs1_code: '49123456789012'
                  latitude: '35.681507'
                  longitude: '139.765581'
        description: ''
      description: |-
        人工呼吸器を登録する。
        このときユーザー識別用トークンが付与されている場合はその組織名を返す。
      tags:
        - ventilator
  /calculate/default_flow:
    get:
      summary: FiO2取得
      tags:
        - calculate
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      air_flow:
                        type: string
                        minLength: 1
                      o2_flow:
                        type: string
                        minLength: 1
                    required:
                      - air_flow
                      - o2_flow
                required:
                  - result
              examples:
                example-1:
                  value:
                    result:
                      air_flow: '12.0'
                      o2_flow: '6.0'
      operationId: get-calculate-default_flow
      parameters:
        - schema:
            type: string
          in: header
          description: 疎通用トークン
          name: X-Api-Token
          required: true
        - schema:
            type: string
          in: header
          name: Accept
          description: application/json
          required: true
        - schema:
            type: string
          in: query
          name: patient_id
          required: true
        - schema:
            type: string
          in: query
          name: airway_pressure
          required: true
      description: 推奨空気流量・酸素流量を取得
  /patient:
    post:
      summary: 患者情報を新しく登録する
      tags:
        - patient
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      patient_id:
                        type: number
                      predicted_vt:
                        type: string
                        minLength: 1
                    required:
                      - patient_id
                      - predicted_vt
                required:
                  - result
              examples:
                example-1:
                  value:
                    result:
                      patient_id: 1
                      predicted_vt: '330'
      operationId: post-patient
      description: 患者情報の新規登録
      parameters:
        - schema:
            type: string
          in: header
          name: X-Api-Token
          description: 疎通用トークン
          required: true
        - schema:
            type: string
          in: header
          name: Accept
          description: application/json
          required: true
        - schema:
            type: string
          in: header
          name: Content-Type
          description: application/json; charset=UTF-8
          required: true
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                patient_code:
                  type: string
                  minLength: 1
                height:
                  type: string
                  minLength: 1
                gender:
                  type: number
                ventilator_id:
                  type: number
              required:
                - height
                - gender
                - ventilator_id
            examples:
              example-1:
                value:
                  patient_code: '999'
                  height: string
                  gender: 1
                  ventilator_id: 1
  /calculate/estimated_data:
    get:
      summary: 予測値取得
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  result:
                    type: object
                    required:
                      - estimated_peep
                      - fio2
                    properties:
                      estimated_peep:
                        type: string
                        minLength: 1
                      fio2:
                        type: string
                        minLength: 1
                required:
                  - result
              examples:
                example-1:
                  value:
                    result:
                      estimated_peep: '7.3'
                      fio2: '47.3'
      operationId: get-calculate-estimated_data
      description: 諸変数を投げて算出可能な予測値を取得する
      parameters:
        - schema:
            type: string
          in: query
          name: airway_pressure
        - schema:
            type: string
          in: query
          name: air_flow
        - schema:
            type: string
          in: query
          name: o2_flow
        - schema:
            type: string
          in: header
          description: 疎通用トークン
          name: X-Api-Token
          required: true
        - schema:
            type: string
          in: header
          name: Accept
          description: application/json
          required: true
      tags:
        - calculate
  '/ventilator/{ventilator_id}':
    parameters:
      - schema:
          type: string
        name: ventilator_id
        in: path
        required: true
    get:
      summary: 呼吸器に紐付けられた関連値データを取得する
      tags:
        - ventilator
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  result:
                    type: object
                    required:
                      - airway_pressure
                      - air_flow
                      - o2_flow
                      - rr
                      - estimated_vt
                      - estimated_mv
                      - estimated_peep
                      - fio2
                    properties:
                      airway_pressure:
                        type: string
                        minLength: 1
                      air_flow:
                        type: string
                        minLength: 1
                      o2_flow:
                        type: string
                        minLength: 1
                      rr:
                        type: string
                        minLength: 1
                      estimated_vt:
                        type: string
                        minLength: 1
                      estimated_mv:
                        type: string
                        minLength: 1
                      estimated_peep:
                        type: string
                        minLength: 1
                      fio2:
                        type: string
                        minLength: 1
                required:
                  - result
              examples:
                example-1:
                  value:
                    result:
                      patient_id: 1
                      airway_pressure: '23.6'
                      air_flow: '12.0'
                      o2_flow: '6.0'
                      rr: '15.9'
                      estimated_vt: '446'
                      estimated_mv: '6.9'
                      estimated_peep: '7.3'
                      fio2: '47.3'
      operationId: get-ventilator-ventilator_id
      parameters:
        - schema:
            type: string
          in: header
          name: X-Api-Token
          description: 疎通用トークン
          required: true
        - schema:
            type: string
          in: header
          name: Accept
          description: application/json
          required: true
      description: 関連値を取得する
    put:
      summary: 最終設定フラグを設定する
      operationId: put-ventilartor_values-id
      description: 最終設定フラグを設定
      parameters:
        - schema:
            type: string
          in: header
          name: X-Api-Token
          description: 疎通用トークン
          required: true
        - schema:
            type: string
          in: header
          name: Accept
          description: application/json
          required: true
        - schema:
            type: string
          in: header
          description: application/json; charset=UTF-8
          name: Content-Type
          required: true
        - schema:
            type: string
          in: header
          name: X-App-Key
          description: アプリキー
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                fixed_flg:
                  type: boolean
              required:
                - fixed_flg
            examples:
              example-1:
                value:
                  fixed_flg: true
      tags:
        - ventilator
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      fixed_flg:
                        type: boolean
                    required:
                      - fixed_flg
                required:
                  - result
              examples:
                example-1:
                  value:
                    result:
                      fixed_flg: true
    post:
      summary: ''
      operationId: post-ventilator-ventilator_id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      ventilator_id:
                        type: number
                      fio2:
                        type: string
                        minLength: 1
                      estimated_vt:
                        type: string
                        minLength: 1
                      estimated_mv:
                        type: string
                        minLength: 1
                      estimated_peep:
                        type: string
                        minLength: 1
                    required:
                      - ventilator_id
                      - fio2
                      - estimated_vt
                      - estimated_mv
                      - estimated_peep
                required:
                  - result
      parameters:
        - schema:
            type: string
          in: header
          description: 疎通用トークン
          name: X-Api-Token
          required: true
        - schema:
            type: string
          in: header
          name: Accept
          description: application/json
          required: true
        - schema:
            type: string
          in: header
          description: application/json; charset=UTF-8
          name: Content-Type
          required: true
        - schema:
            type: string
          in: header
          name: X-App-Key
          description: アプリキー
          required: true
        - schema:
            type: string
          in: header
          name: X-User-Token
          description: ユーザートークン
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                patient_id:
                  type: number
                airway_pressure:
                  type: string
                  minLength: 1
                air_flow:
                  type: string
                  minLength: 1
                o2_flow:
                  type: string
                  minLength: 1
                rr:
                  type: string
                  minLength: 1
                i_avg:
                  type: string
                  minLength: 1
                e_avg:
                  type: string
                  minLength: 1
                predicted_vt:
                  type: string
                  minLength: 1
              required:
                - patient_id
                - airway_pressure
                - air_flow
                - o2_flow
                - rr
                - i_avg
                - e_avg
                - predicted_vt
      description: |-
        関連値を登録する。人工呼吸器が未登録の場合はそのデータも一緒に登録する。
        ventilator_idを持たない場合はventilator_dataを必須とし呼吸器登録を行う。
        X-User-Tokenを持つ場合はユーザー特定してventilator_values.user_idも登録する。
      tags:
        - ventilator
  '/patient/{patient_id}':
    parameters:
      - schema:
          type: string
        name: patient_id
        in: path
        required: true
    get:
      summary: 患者データを取得する
      tags:
        - patient
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  result:
                    type: object
                    required:
                      - gender
                      - predicted_vt
                      - height
                    properties:
                      patient_code:
                        type: string
                        minLength: 1
                      gender:
                        type: number
                      predicted_vt:
                        type: number
                      height:
                        type: string
                        minLength: 1
                required:
                  - result
              examples:
                example-1:
                  value:
                    result:
                      patient_code: '999'
                      gender: 1
                      predicted_vt: 393
                      height: '169.5'
      operationId: get-patient-id
      parameters:
        - schema:
            type: string
          in: header
          name: X-Api-Token
          description: 疎通用トークン
          required: true
        - schema:
            type: string
          in: header
          name: Accept
          description: application/json
          required: true
      description: 患者データを取得する
    put:
      summary: 患者データを更新する
      tags:
        - patient
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  result:
                    type: object
                    required:
                      - gender
                      - predicted_vt
                      - height
                    properties:
                      patient_code:
                        type: string
                        minLength: 1
                      gender:
                        type: number
                      predicted_vt:
                        type: number
                      height:
                        type: string
                        minLength: 1
                required:
                  - result
              examples:
                example-1:
                  value:
                    result:
                      patient_code: '999'
                      gender: 1
                      predicted_vt: 393
                      height: '169.5'
      operationId: put-patient-id
      parameters:
        - schema:
            type: string
          in: header
          name: X-Api-Token
          description: 疎通用トークン
          required: true
        - schema:
            type: string
          in: header
          name: Accept
          description: application/json
          required: true
        - schema:
            type: string
          in: header
          name: Content-Type
          description: application/json; charset=UTF-8
          required: true
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                patient_code:
                  type: string
                  minLength: 1
                height:
                  type: string
                  minLength: 1
                gender:
                  type: number
              required:
                - height
                - gender
            examples:
              example-1:
                value:
                  patient_code: '999'
                  height: '169.5'
                  gender: 1
      description: 患者データを更新する
  /calculate/ie/manual:
    parameters: []
    post:
      summary: ''
      operationId: post-calculate-ie-manual
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      i_avg:
                        type: string
                        minLength: 1
                      e_avg:
                        type: string
                        minLength: 1
                      rr:
                        type: string
                        minLength: 1
                    required:
                      - i_avg
                      - e_avg
                      - rr
                required:
                  - result
              examples:
                example-1:
                  value:
                    result:
                      i_avg: '2.2'
                      e_avg: '1.2'
                      rr: '17.6'
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                data:
                  type: array
                  uniqueItems: true
                  minItems: 2
                  items:
                    type: object
                    properties:
                      i:
                        type: string
                        minLength: 1
                      e:
                        type: string
                        minLength: 1
                    required:
                      - i
                      - e
              required:
                - data
            examples:
              example-1:
                value:
                  data:
                    - i: '***'
                      e: '***'
                    - i: '****'
                      e: '****'
          application/xml:
            schema:
              type: object
              properties: {}
          multipart/form-data:
            schema:
              description: ''
              type: object
              properties:
                data:
                  type: array
                  uniqueItems: true
                  minItems: 1
                  items:
                    required:
                      - i
                      - e
                    properties:
                      i:
                        type: string
                        minLength: 1
                      e:
                        type: string
                        minLength: 1
              required:
                - data
        description: ''
      parameters:
        - schema:
            type: string
          in: header
          name: X-Api-Token
          description: 疎通用トークン
          required: true
        - schema:
            type: string
          in: header
          name: Accept
          description: application/json
          required: true
        - schema:
            type: string
          in: header
          name: Content-Type
          description: application/json; charset=UTF-8
          required: true
      description: 手動測定による呼気、吸気時間をもとにI/Eを取得
      tags:
        - calculate
  /calculate/ie/sound:
    parameters: []
    post:
      summary: ''
      operationId: post-calculate-ie-sound
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      i_avg:
                        type: string
                        minLength: 1
                      e_avg:
                        type: string
                        minLength: 1
                      rr:
                        type: string
                        minLength: 1
                required:
                  - result
              examples:
                example-1:
                  value:
                    result:
                      i_avg: '2.2'
                      e_avg: '1.2'
                      rr: '17.6'
      description: 音声ファイルをもとにI/Eを取得
      parameters:
        - schema:
            type: string
          in: header
          name: X-Api-Token
          description: 疎通用トークン
          required: true
        - schema:
            type: string
          in: header
          name: Accept
          description: application/json
          required: true
        - schema:
            type: string
          in: header
          name: Content-Type
          description: application/json; charset=UTF-8
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sound:
                  type: object
                  required:
                    - content_type
                    - filename
                    - file_data
                  properties:
                    content_type:
                      type: string
                    filename:
                      type: string
                    file_data:
                      type: string
                os:
                  type: string
              required:
                - sound
                - os
        description: ''
      tags:
        - calculate
  /auth/token/remove:
    put:
      summary: ''
      operationId: put-auth-token-remove
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      user_id:
                        type: number
                    required:
                      - user_id
                required:
                  - result
              examples:
                example-1:
                  value:
                    result:
                      user_id: 3
      description: logout
      parameters:
        - schema:
            type: string
          in: header
          name: X-Api-Token
          required: true
        - schema:
            type: string
          in: header
          name: X-User-Token
          required: true
        - schema:
            type: string
          in: header
          name: Accept
          description: application/json
          required: true
      tags:
        - auth
  /appkey:
    post:
      summary: ''
      operationId: post-appkey
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  appkey:
                    type: string
                    minLength: 1
                required:
                  - appkey
      description: 初回利用時にidfvをもとにアプリキー発行
      parameters:
        - schema:
            type: string
          in: header
          description: 疎通用トークン
          name: X-Api-Token
          required: true
        - schema:
            type: string
          in: header
          name: Accept
          description: application/json
          required: true
        - schema:
            type: string
          in: header
          description: application/json; charset=UTF-8
          name: Content-Type
          required: true
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                idfv:
                  type: string
                  minLength: 1
              required:
                - idfv
      tags:
        - appkey
    parameters: []
  /user:
    get:
      summary: Your GET endpoint
      tags:
        - user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  result:
                    type: object
                    required:
                      - user_name
                      - organization_name
                    properties:
                      user_name:
                        type: string
                        minLength: 1
                      organization_name:
                        type: string
                        minLength: 1
                      email:
                        type: string
                        minLength: 1
                required:
                  - result
              examples:
                example-1:
                  value:
                    result:
                      user_name: テスト太郎
                      organization_name: テスト組織
                      email: test@email.com
      operationId: get-user
      parameters:
        - schema:
            type: string
          in: header
          name: X-Api-Token
          description: 疎通用トークン
          required: true
        - schema:
            type: string
          in: header
          name: X-User_Token
          description: ユーザー識別用トークン
          required: true
        - schema:
            type: string
          in: header
          required: true
          name: Accept
          description: application/json
      description: ユーザートークンからユーザー情報を取得する
    put:
      summary: ''
      operationId: put-user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      user_name:
                        type: string
                        minLength: 1
                      email:
                        type: string
                        minLength: 1
                required:
                  - result
              examples:
                example-1:
                  value:
                    result:
                      user_name: テスト太郎
                      email: test@email.com
      description: ユーザートークンからユーザー情報を更新する
      parameters:
        - schema:
            type: string
          in: header
          name: X-Api-Token
          description: 疎通用トークン
          required: true
        - schema:
            type: string
          in: header
          name: X-User-Token
          description: ユーザー識別用トークン
          required: true
        - schema:
            type: string
          in: header
          required: true
          name: Accept
          description: application/json
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                user_name:
                  type: string
                  minLength: 1
                email:
                  type: string
                  minLength: 1
            examples:
              example-1:
                value:
                  user_name: テスト太郎
                  email: test@email.com
        description: ''
      tags:
        - user
  '/patient/{patient_id}/detail':
    parameters:
      - schema:
          type: string
        name: patient_id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags:
        - patient
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  result:
                    type: object
                    required:
                      - has_observed
                    properties:
                      has_observed:
                        type: boolean
                      observed_at:
                        type: string
                        minLength: 1
                      opt_out_flg:
                        type: number
                      patient_code:
                        type: string
                        minLength: 1
                      age:
                        type: string
                        minLength: 1
                      vent_disease_name:
                        type: string
                        minLength: 1
                      other_disease_name_1:
                        type: string
                        minLength: 1
                      other_disease_name_2:
                        type: string
                        minLength: 1
                      userd_place:
                        type: number
                      hospital_name:
                        type: string
                        minLength: 1
                      national_name:
                        type: string
                        minLength: 1
                      discontinuation_at:
                        type: string
                        minLength: 1
                      outcome:
                        type: number
                      treatment:
                        type: number
                      adverse_event_flg:
                        type: number
                      adverse_event_contents:
                        type: string
                        minLength: 1
                required:
                  - result
              examples:
                患者観察研究データ入力済みの場合:
                  value:
                    result:
                      has_observed: true
                      observed_at: '2021-02-08 12:34:06'
                      opt_out_flg: 1
                      patient_code: '999'
                      age: '21'
                      vent_disease_name: XXXXXX
                      other_disease_name_1: xXXXXX
                      other_disease_name_2: XXXXXX
                      userd_place: 3
                      hospital_name: XXXXXX
                      national_name: XXXXXX
                      discontinuation_at: '2021-04-08 17:04:01'
                      outcome: 1
                      treatment: 1
                      adverse_event_flg: 1
                      adverse_event_contents: XXXXXX
                患者観察研究データ未入力の場合:
                  value:
                    result:
                      has_observed: false
      operationId: get-patient-patient_id-detail
      parameters:
        - schema:
            type: string
          in: header
          name: X-Api-Token
          required: true
        - schema:
            type: string
          in: header
          name: X-User-Token
          required: true
        - schema:
            type: string
          in: header
          name: Accept
          description: application/json
          required: true
      description: 患者観察研究データの存在確認及び最新データ取得
    post:
      summary: ''
      operationId: post-patient-patient_id-detail
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      observed_at:
                        type: string
                        minLength: 1
                      patient_code:
                        type: string
                        minLength: 1
                    required:
                      - observed_at
                      - patient_code
                required:
                  - result
              examples:
                example-1:
                  value:
                    result:
                      observed_at: '2021-02-08 12:34:06'
                      patient_code: '999'
      description: 患者観察研究データの登録
      parameters:
        - schema:
            type: string
          in: header
          name: X-Api-Token
          required: true
        - schema:
            type: string
          in: header
          name: X-User-Token
          required: true
        - schema:
            type: string
          in: header
          required: true
          name: Accept
          description: application/json
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                opt_out_flg:
                  type: number
                age:
                  type: string
                  minLength: 1
                vent_disease_name:
                  type: string
                  minLength: 1
                other_disease_name_1:
                  type: string
                  minLength: 1
                other_disease_name_2:
                  type: string
                  minLength: 1
                userd_place:
                  type: number
                hospital_name:
                  type: string
                  minLength: 1
                national_name:
                  type: string
                  minLength: 1
                discontinuation_at:
                  type: string
                  minLength: 1
                outcome:
                  type: number
                treatment:
                  type: number
                adverse_event_flg:
                  type: number
                adverse_event_contents:
                  type: string
                  minLength: 1
            examples:
              example-1:
                value:
                  opt_out_flg: 1
                  age: '21'
                  vent_disease_name: XXXXXX
                  other_disease_name_1: xXXXXX
                  other_disease_name_2: XXXXXX
                  userd_place: 3
                  hospital_name: XXXXXX
                  national_name: XXXXXX
                  discontinuation_at: '2021-04-08 17:04:01'
                  outcome: 1
                  treatment: 1
                  adverse_event_flg: 1
                  adverse_event_contents: XXXXXX
      tags:
        - patient
    put:
      summary: ''
      operationId: put-patient-patient_id-detail
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      observed_at:
                        type: string
                        minLength: 1
                      patient_code:
                        type: string
                        minLength: 1
                    required:
                      - observed_at
                      - patient_code
                required:
                  - result
              examples:
                example-1:
                  value:
                    result:
                      observed_at: '2021-02-08 12:34:06'
                      patient_code: '999'
      description: 患者観察研究データの更新
      parameters:
        - schema:
            type: string
          in: header
          name: X-Api-Token
          required: true
        - schema:
            type: string
          in: header
          name: X-User-Token
          required: true
        - schema:
            type: string
          in: header
          name: Accept
          description: application/json
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                opt_out_flg:
                  type: number
                age:
                  type: string
                  minLength: 1
                vent_disease_name:
                  type: string
                  minLength: 1
                other_disease_name_1:
                  type: string
                  minLength: 1
                other_disease_name_2:
                  type: string
                  minLength: 1
                userd_place:
                  type: number
                hospital_name:
                  type: string
                  minLength: 1
                national_name:
                  type: string
                  minLength: 1
                discontinuation_at:
                  type: string
                  minLength: 1
                outcome:
                  type: number
                treatment:
                  type: number
                adverse_event_flg:
                  type: number
                adverse_event_contents:
                  type: string
                  minLength: 1
            examples:
              example-1:
                value:
                  opt_out_flg: 1
                  age: '21'
                  vent_disease_name: XXXXXX
                  other_disease_name_1: xXXXXX
                  other_disease_name_2: XXXXXX
                  userd_place: 3
                  hospital_name: XXXXXX
                  national_name: XXXXXX
                  discontinuation_at: '2021-04-08 17:04:01'
                  outcome: 1
                  treatment: 1
                  adverse_event_flg: 1
                  adverse_event_contents: XXXXXX
      tags:
        - patient
  /ventilator_value:
    parameters: []
    get:
      summary: Your GET endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  result:
                    type: object
                    required:
                      - has_observed
                    properties:
                      has_observed:
                        type: boolean
                      ventilator_value_id:
                        type: number
                      observed_at:
                        type: string
                      observed_user_name:
                        type: string
                      nearest_city:
                        type: string
                      gender:
                        type: number
                      height:
                        type: string
                      ideal_weight:
                        type: string
                      airway_pressure:
                        type: string
                      total_flow:
                        type: string
                      air_flow:
                        type: string
                      o2_flow:
                        type: string
                      rr:
                        type: string
                      expiratory_time:
                        type: string
                      inspiratory_time:
                        type: string
                      vt_per_kg:
                        type: string
                      predicted_vt:
                        type: string
                      estimated_vt:
                        type: string
                      estimated_mv:
                        type: string
                      estimated_peep:
                        type: string
                      fio2:
                        type: string
                      status_use:
                        type: number
                      status_use_other:
                        type: string
                      spo2:
                        type: string
                      etco2:
                        type: string
                      pao2:
                        type: string
                      paco2:
                        type: string
                      bug_flg:
                        type: number
                      bug_name:
                        type: string
                      bug_detail:
                        type: string
                required:
                  - result
              examples:
                example-1:
                  value:
                    result:
                      has_observed: true
                      ventilator_value_id: 1
                      observed_at: ''
                      observed_user_name: ''
                      nearest_city: ''
                      gender: 1
                      height: ''
                      ideal_weight: ''
                      airway_pressure: ''
                      total_flow: ''
                      air_flow: ''
                      o2_flow: ''
                      rr: ''
                      expiratory_time: ''
                      inspiratory_time: ''
                      vt_per_kg: ''
                      predicted_vt: ''
                      estimated_vt: ''
                      estimated_mv: ''
                      estimated_peep: ''
                      fio2: ''
                      status_use: 1
                      status_use_other: ''
                      spo2: ''
                      etco2: ''
                      pao2: ''
                      paco2: ''
                      bug_flg: 1
                      bug_name: ''
                      bug_detail: ''
                example-2:
                  value:
                    result:
                      has_observed: false
      operationId: get-ventilator_value
      description: |-
        ventilator_idのみ指定で該当呼吸器に対する機器観察研究データの存在確認及び最新データ取得
        ventilator_value_idの指定があれば該当ventilator_value_idの機器観察研究データ取得
      parameters:
        - schema:
            type: string
          in: header
          name: X-Api-Token
          required: true
        - schema:
            type: string
          in: header
          name: X-User-Token
          required: true
        - schema:
            type: string
          in: header
          name: Accept
          description: application/json
          required: true
        - schema:
            type: string
          in: query
          name: ventilator_id
        - schema:
            type: string
          in: query
          name: ventilator_value_id
      tags:
        - ventilator_value
    put:
      summary: ''
      operationId: put-ventilator_value_id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      revised_at:
                        type: string
                    required:
                      - revised_at
                required:
                  - result
              examples:
                example-1:
                  value:
                    result:
                      revised_at: ''
      description: 該当ventilator_value_idに対する機器観察研究データの更新
      parameters:
        - schema:
            type: string
          in: header
          name: X-Api-Token
          required: true
        - schema:
            type: string
          in: header
          name: X-User-Token
          required: true
        - schema:
            type: string
          in: header
          name: Accept
          description: application/json
          required: true
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                ventilator_value_id:
                  type: number
                observed_at:
                  type: string
                gender:
                  type: number
                height:
                  type: string
                ideal_weight:
                  type: string
                airway_pressure:
                  type: string
                air_flow:
                  type: string
                o2_flow:
                  type: string
                status_use:
                  type: number
                status_use_other:
                  type: string
                spo2:
                  type: string
                etco2:
                  type: string
                pao2:
                  type: string
                paco2:
                  type: string
              required:
                - ventilator_value_id
            examples:
              example-1:
                value:
                  ventilator_value_id: 1
                  observed_at: ''
                  nearest_city: ''
                  gender: 1
                  height: ''
                  ideal_weight: ''
                  airway_pressure: ''
                  total_flow: ''
                  air_flow: ''
                  o2_flow: ''
                  rr: ''
                  expiratory_time: ''
                  inspiratory_time: ''
                  vt_per_kg: ''
                  predicted_vt: ''
                  estimated_vt: ''
                  estimated_mv: ''
                  estimated_peep: ''
                  fio2: ''
                  status_use: 1
                  status_use_other: ''
                  spo2: ''
                  etco2: ''
                  pao2: ''
                  paco2: ''
                  bug_flg: 1
                  bug_name: ''
                  bug_detail: ''
      tags:
        - ventilator_value
  /ventilator_value/list:
    get:
      summary: Your GET endpoint
      tags:
        - ventilator_value
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  result:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      required:
                        - id
                        - observed_at
                        - observed_user_name
                      properties:
                        id:
                          type: number
                        observed_at:
                          type: string
                          minLength: 1
                        observed_user_name:
                          type: string
                          minLength: 1
                required:
                  - result
              examples:
                example-1:
                  value:
                    result:
                      - id: 10
                        observed_at: '2021-02-04 12:34:06'
                        observed_user_name: test_user
                      - id: 22
                        observed_at: '2021-02-06 12:34:06'
                        observed_user_name: test_user
                      - id: 33
                        observed_at: '2021-02-07 12:34:06'
                        observed_user_name: test_user
      operationId: get-ventilator_value-list
      description: '該当呼吸器に対するfixed_flgが立っているventilator_value_idおよびそれぞれのobserved_at,observed_user_nameの値を返す'
      parameters:
        - schema:
            type: string
          in: header
          name: X-Api-Token
        - schema:
            type: string
          in: header
          name: Accept
          description: application/json
        - schema:
            type: string
          in: query
          name: ventilator_id
          required: true
        - schema:
            type: string
          in: query
          name: limit
        - schema:
            type: string
          in: query
          name: offset
    parameters: []
components:
  schemas: {}
tags:
  - name: appkey
  - name: auth
  - name: calculate
  - name: patient
  - name: user
  - name: ventilator
  - name: ventilator_value
